export const UPDATE_SOCKET='update-socket'
export const UPDATE_USER_LIST='update-user-list'
export const UPDATE_ORANGE_CLICK='update-orange'
export const UPDATE_BLUE_CLICK='update-blue'
export const RESET_CHART='reset-chart'